django_project/test_task/test_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("video.urls")),
]
if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

django_project/test_task/video/urls.py
from django.urls import path

from .views import (
    video_run_string,
    VideoListView,
    VideoCreateView,
    VideoDetailView,
    VideoDeleteView,
)

app_name = "video"

urlpatterns = [
    path("video/", VideoListView.as_view(), name="list_video"),
    path("video/add/", video_run_string, name="add_video"),
    path("video/create/", VideoCreateView.as_view(), name="create_video"),
    path("video/<slug:slug>/", VideoDetailView.as_view(), name="detail_video"),
    path("video/<slug:slug>/delete/", VideoDeleteView.as_view(), name="delete_video"),
]

django_project/test_task/video/models.py
from django.db import models


class VideoFile(models.Model):
    run_string = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)
    file = models.FileField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

django_project/test_task/video/views.py
from django.http import HttpRequest, HttpResponse, Http404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView

from video.models import VideoFile
from video.utils import create_file


def video_run_string(request: HttpRequest) -> HttpResponse:
    run_string = request.GET.get("text", None)
    if run_string is None:
        raise Http404
    return create_file(run_string)


class VideoListView(ListView):
    queryset = VideoFile.objects.all().order_by("-created_at")


class VideoCreateView(CreateView):
    model = VideoFile
    fields = ["run_string"]

    def post(self, request, *args, **kwargs):
        run_string = request.POST.get("run_string", None)
        if run_string is None:
            raise Http404
        return create_file(run_string)


class VideoDetailView(DetailView):
    model = VideoFile


class VideoDeleteView(DeleteView):
    model = VideoFile
    success_url = reverse_lazy("video:list_video")

django_project/test_task/video/templates/video/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
    <br>
</head>

<body>
{% block body %}
Base Body
{% endblock %}
<br>
</body>
<footer>
    <div>

        {% now 'l' as current_weekday%}
        Today is {{ current_weekday }}
    </div>
    <br>
    <div>
        {% now 'd M Y' %}
    </div>

    <div>
        {% now 'H:i' %}
    </div>
</footer>
</html>

django_project/test_task/video/templates/video/videofile_confirm_delete.html
{% extends 'video/base.html' %}

{% block title %}
Confirm archive {{ object.slug }}
{% endblock %}

{% block body %}
<div>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.slug }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</div>
<br>
<div>
    <a href="{% url 'video:detail_video' slug=object.slug %}">Back to video</a>
</div>
{% endblock %}

django_project/test_task/video/templates/video/videofile_detail.html
{% extends 'video/base.html' %}

{% block title %}
Video #{{ object.run_string }}
{% endblock %}

{% block body %}
<h1>Video <strong>{{ object.run_string }}</strong></h1>
<div>
    <div>
        Run_string: {{ object.run_string }}
    </div>
    <div>
        <video controls width="300" height="300">
            <source src="{{ object.file.url }}" type="video/mp4">

        </video>
    </div>
    <div>
        Download file: <a href="{{ object.file.url }}" download> {{ object.file }}</a>
    </div>
    <div>Created at: {{ object.created_at}}</div>

</div>
<br>


<div>
    <a href="{% url 'video:delete_video' slug=object.slug %}">Delete video</a>
</div>
<br>
<div>
    <a href="{% url 'video:list_video' %}">Back to video list</a>
</div>
{% endblock %}

django_project/test_task/video/templates/video/videofile_form.html
{% extends 'video/base.html' %}

{% block title %}
    Create video
{% endblock %}

{% block body %}
<h1>Create a new video:</h1>

<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</div>
<br>
<div>
    <a href="{% url 'video:list_video' %}">Back to video list</a>
</div>
{% endblock %}

django_project/test_task/video/templates/video/videofile_list.html
{% extends 'video/base.html' %}

{% block title %}
Video List
{% endblock %}

{% block body %}
<h1>Video:</h1>

<div>

    {% if not object_list %}
    <h3>No video yet</h3>
    {% else %}
    {% for video in object_list%}

    <div>
        <p>run_string: <a href="{% url 'video:detail_video' slug=video.slug %}">
             {{ video.run_string }}</a></p>
        <p>file: {{ video.file }}</p>
        <p>created_at: {{ video.created_at }}</p>
    </div>
    <br>
    {% endfor %}

    {% endif %}
</div>

<div>
    <a href="{% url 'video:create_video' %}">Create a new video</a>
</div>

{% endblock %}